# Generated by Django 4.1.2 on 2022-10-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_country', models.CharField(max_length=50)),
                ('player_race', models.CharField(choices=[('Terran', 'Terran'), ('Protoss', 'Protoss'), ('Zerg', 'Zerg')], max_length=50)),
                ('rating', models.IntegerField(default=1000)),
            ],
        ),
    ]
