# Generated by Django 4.1.2 on 2022-10-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aligulacv2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player_a_score', models.IntegerField(default=0)),
                ('player_b_score', models.IntegerField(default=0)),
                ('player_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_a', to='aligulacv2.player_stats')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='aligulacv2.player_stats')),
            ],
        ),
    ]
