# Generated by Django 4.1.2 on 2022-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligulacv2', '0002_match_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player_id', models.IntegerField(default=1)),
                ('player', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
