# Generated by Django 4.1.2 on 2022-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aligulacv2', '0006_match_history_player_a_rating_v_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_history',
            name='best_of',
            field=models.IntegerField(default=1),
        ),
    ]
