# Generated by Django 4.1.2 on 2022-11-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aligulacv2', '0007_match_history_best_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
